import type { ComponentType } from "react";
import type { MiniArchProps } from "./types";
import {
  MiniLeNet,
  MiniAlexNet,
  MiniVGG,
  MiniGoogLeNet,
  MiniResNet,
  MiniDenseNet,
  MiniEfficientNet,
  MiniConvNeXt,
  MiniRNN,
  MiniLSTM,
  MiniGRU,
  MiniSeq2Seq,
  MiniAttention,
  MiniTransformer,
  MiniTransformerXL,
  MiniSparseAttention,
  MiniRoPE,
  MiniFlashAttention,
  MiniGPT1,
  MiniGPT2,
  MiniGPT3,
  MiniScalingLaws,
  MiniGPT4Llama,
  MiniLearningToSummarize,
  MiniInstructGPT,
  MiniConstitutionalAI,
  MiniDPO,
  MiniBERT,
  MiniRoBERTa,
  MiniALBERT,
  MiniDistilBERT,
  MiniViT,
  MiniDeiT,
  MiniSwin,
  MiniDiT,
  MiniDDPM,
  MiniLDM,
  MiniImagen,
  MiniFlowMatching,
  MiniCLIP,
  MiniBLIP,
  MiniFlamingo,
  MiniLLaVA,
  MiniCoT,
  MiniSelfConsistency,
  MiniO1,
  MiniDeepSeekR1,
} from ".";

const MAP: Record<string, ComponentType<MiniArchProps>> = {
  "01-lenet": MiniLeNet,
  "02-alexnet": MiniAlexNet,
  "03-vgg": MiniVGG,
  "04-inception": MiniGoogLeNet,
  "05-resnet": MiniResNet,
  "06-densenet": MiniDenseNet,
  "07-efficientnet": MiniEfficientNet,
  "08-convnext": MiniConvNeXt,
  "01-rnn": MiniRNN,
  "02-lstm": MiniLSTM,
  "03-gru": MiniGRU,
  "04-seq2seq": MiniSeq2Seq,
  "05-attention": MiniAttention,
  "01-transformer": MiniTransformer,
  "02-transformer-xl": MiniTransformerXL,
  "03-sparse-attention": MiniSparseAttention,
  "04-rope": MiniRoPE,
  "05-flash-attention": MiniFlashAttention,
  "01-gpt1": MiniGPT1,
  "02-gpt2": MiniGPT2,
  "03-gpt3": MiniGPT3,
  "04-scaling-laws": MiniScalingLaws,
  "05-gpt4-llama": MiniGPT4Llama,
  "01-learning-to-summarize": MiniLearningToSummarize,
  "02-instructgpt": MiniInstructGPT,
  "03-constitutional-ai": MiniConstitutionalAI,
  "04-dpo": MiniDPO,
  "01-bert": MiniBERT,
  "02-roberta": MiniRoBERTa,
  "03-albert": MiniALBERT,
  "04-distilbert": MiniDistilBERT,
  "01-vit": MiniViT,
  "02-deit": MiniDeiT,
  "03-swin": MiniSwin,
  "04-dit": MiniDiT,
  "01-ddpm": MiniDDPM,
  "02-ldm": MiniLDM,
  "03-imagen": MiniImagen,
  "04-flow-matching": MiniFlowMatching,
  "01-clip": MiniCLIP,
  "02-blip": MiniBLIP,
  "03-flamingo": MiniFlamingo,
  "04-llava": MiniLLaVA,
  "01-cot": MiniCoT,
  "02-self-consistency": MiniSelfConsistency,
  "03-o1": MiniO1,
  "04-deepseek-r1": MiniDeepSeekR1,
};

export function getMiniArch(
  nodePath: string
): ComponentType<MiniArchProps> | null {
  const slug = nodePath.split("/").pop()?.replace(/\.md$/, "") ?? "";
  return MAP[slug] ?? null;
}
