import { lazy } from "react";
import type { ComponentType, LazyExoticComponent } from "react";

export const goldenSamples: Record<
  string,
  LazyExoticComponent<ComponentType>
> = {
  "01-cnn/05-resnet": lazy(() => import("./resnet/NodePageResNet")),
  "05-transformer/01-transformer": lazy(
    () => import("./transformer/NodePageTransformer"),
  ),
  "10-diffusion/01-ddpm": lazy(() => import("./ddpm/NodePageDDPM")),
  "11-peft-lora/03-lora": lazy(() => import("./lora/NodePageLoRA")),
  "06-bert-family/01-bert": lazy(() => import("./bert/NodePageBERT")),
  "09-multimodal-clip/01-clip": lazy(() => import("./clip/NodePageCLIP")),
  "07-gpt-scaling/03-gpt3": lazy(() => import("./gpt3/NodePageGPT3")),
  "04-gan/01-gan": lazy(() => import("./gan/NodePageGAN")),
  "08-vit/01-vit": lazy(() => import("./vit/NodePageViT")),
  "15-reasoning-o1-r1/01-cot": lazy(() => import("./cot/NodePageCoT")),
  "12-rlhf-alignment/02-instructgpt": lazy(() => import("./instructgpt/NodePageInstructGPT")),
  "14-rag-agent/01-rag": lazy(() => import("./rag/NodePageRAG")),
  "13-moe-efficient/03-mixtral": lazy(() => import("./mixtral/NodePageMixtral")),
  "02-rnn-lstm/02-lstm": lazy(() => import("./lstm/NodePageLSTM")),
  "03-word-embedding/01-word2vec": lazy(() => import("./word2vec/NodePageWord2Vec")),
  "01-cnn/02-alexnet": lazy(() => import("./alexnet/NodePageAlexNet")),
  "10-diffusion/02-ldm": lazy(() => import("./ldm/NodePageLDM")),
  "07-gpt-scaling/02-gpt2": lazy(() => import("./gpt2/NodePageGPT2")),
  "12-rlhf-alignment/04-dpo": lazy(() => import("./dpo/NodePageDPO")),
  "02-rnn-lstm/05-attention": lazy(() => import("./bahdanau/NodePageBahdanau")),
  "10-diffusion/05-dit": lazy(() => import("./dit/NodePageDiT")),
  "07-gpt-scaling/04-scaling-laws": lazy(() => import("./scaling-laws/NodePageScalingLaws")),
  "04-gan/04-stylegan": lazy(() => import("./stylegan/NodePageStyleGAN")),
  "03-word-embedding/04-elmo": lazy(() => import("./elmo/NodePageELMo")),
  "07-gpt-scaling/01-gpt1": lazy(() => import("./gpt1/NodePageGPT1")),
  "02-rnn-lstm/03-gru": lazy(() => import("./gru/NodePageGRU")),
  "02-rnn-lstm/04-seq2seq": lazy(() => import("./seq2seq/NodePageSeq2Seq")),
  "10-diffusion/03-imagen": lazy(() => import("./imagen/NodePageImagen")),
  "09-multimodal-clip/03-flamingo": lazy(() => import("./flamingo/NodePageFlamingo")),
  "08-vit/03-swin": lazy(() => import("./swin/NodePageSwin")),
  "05-transformer/04-rope": lazy(() => import("./rope/NodePageRoPE")),
  "02-rnn-lstm/01-rnn": lazy(() => import("./rnn/NodePageRNN")),
  "03-word-embedding/02-glove": lazy(() => import("./glove/NodePageGloVe")),
  "05-transformer/03-sparse-attention": lazy(() => import("./sparse-attention/NodePageSparseAttention")),
  "03-word-embedding/03-fasttext": lazy(() => import("./fasttext/NodePageFastText")),
  "05-transformer/05-flash-attention": lazy(() => import("./flash-attention/NodePageFlashAttention")),
  "15-reasoning-o1-r1/03-o1": lazy(() => import("./o1/NodePageO1")),
  "15-reasoning-o1-r1/04-deepseek-r1": lazy(() => import("./deepseek-r1/NodePageDeepSeekR1")),
  "06-bert-family/02-roberta": lazy(() => import("./roberta/NodePageRoBERTa")),
  "11-peft-lora/04-qlora": lazy(() => import("./qlora/NodePageQLoRA")),
  "06-bert-family/03-albert": lazy(() => import("./albert/NodePageALBERT")),
  "05-transformer/02-transformer-xl": lazy(() => import("./transformer-xl/NodePageTransformerXL")),
  "12-rlhf-alignment/03-constitutional-ai": lazy(() => import("./constitutional-ai/NodePageConstitutionalAI")),
  "04-gan/02-dcgan": lazy(() => import("./dcgan/NodePageDCGAN")),
  "07-gpt-scaling/05-gpt4-llama": lazy(() => import("./gpt4-llama/NodePageGPT4LLaMA")),
  "06-bert-family/04-distilbert": lazy(() => import("./distilbert/NodePageDistilBERT")),
  "13-moe-efficient/02-switch-transformer": lazy(() => import("./switch-transformer/NodePageSwitchTransformer")),
  "04-gan/03-cyclegan": lazy(() => import("./cyclegan/NodePageCycleGAN")),
  "08-vit/02-deit": lazy(() => import("./deit/NodePageDeiT")),
  "09-multimodal-clip/02-blip": lazy(() => import("./blip/NodePageBLIP")),
  "14-rag-agent/02-react": lazy(() => import("./react/NodePageReAct")),
  "09-multimodal-clip/04-llava": lazy(() => import("./llava/NodePageLLaVA")),
  "14-rag-agent/03-toolformer": lazy(() => import("./toolformer/NodePageToolformer")),
  "14-rag-agent/04-autogpt": lazy(() => import("./autogpt/NodePageAutoGPT")),
  "15-reasoning-o1-r1/02-self-consistency": lazy(() => import("./self-consistency/NodePageSelfConsistency")),
  "12-rlhf-alignment/01-learning-to-summarize": lazy(() => import("./learning-to-summarize/NodePageLearningToSummarize")),
  "10-diffusion/04-flow-matching": lazy(() => import("./flow-matching/NodePageFlowMatching")),
  "13-moe-efficient/04-deepseek-v3": lazy(() => import("./deepseek-v3/NodePageDeepSeekV3")),
  "01-cnn/01-lenet": lazy(() => import("./lenet/NodePageLenet")),
  "01-cnn/08-convnext": lazy(() => import("./convnext/NodePageConvnext")),
  "11-peft-lora/01-adapter": lazy(() => import("./adapter/NodePageAdapter")),
  "13-moe-efficient/01-sparsely-gated-moe": lazy(() => import("./sparsely-gated-moe/NodePageSparselyGatedMoe")),
  "01-cnn/03-vgg": lazy(() => import("./vgg/NodePageVgg")),
  "01-cnn/04-inception": lazy(() => import("./inception/NodePageInception")),
  "01-cnn/06-densenet": lazy(() => import("./densenet/NodePageDensenet")),
  "01-cnn/07-efficientnet": lazy(() => import("./efficientnet/NodePageEfficientnet")),
  "11-peft-lora/02-prefix-tuning": lazy(() => import("./prefix-tuning/NodePagePrefixTuning")),
};
